### ISSUE TITLE
Module `path` does not exist in the Haste module map

### ISSUE THREAD

**Issue by Alferdize** [kentcdodds/babel-plugin-macros#106]
* `babel-plugin-macros` version:2.5.0
* `node` version:v11.11.0
* `npm` (or `yarn`) version:6.7.0
Relevant code or config

```javascript
```

What you did: I was using lingui/js-lingui for language translation after successful installation. I got and error while running my app.

What happened:It gave me an error Module `path` does not exist in the Haste module map

error: bundling failed: Error: Unable to resolve module `path` from `/Users/evotan/anubhav/testing/node_modules/ba
bel-plugin-macros/dist/index.js`: Module `path` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/evotan/anubhav/testing/node_modules/metro/src/node-haste/Dependenc
yGraph/ModuleResolution.js:183:15)
    at ResolutionRequest.resolveDependency (/Users/evotan/anubhav/testing/node_modules/metro/src/node-haste/Depend
encyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/evotan/anubhav/testing/node_modules/metro/src/node-haste/Dependen
cyGraph.js:283:16)
    at Object.resolve (/Users/evotan/anubhav/testing/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at dependencies.map.result (/Users/evotan/anubhav/testing/node_modules/metro/src/DeltaBundler/traverseDependen
cies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/evotan/anubhav/testing/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users/evotan/anubhav/testing/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/evotan/anubhav/testing/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
 DELTA  [android, dev] ./index.js ▓▓▓▓▓░░░░░░░░░░░ 33.8% (306/526), failed.

Please Help!

**Comment by kentcdodds** [comment]
Sorry, I have no idea what this could be.

**Comment by andreialecu** [comment]
I'm using react-native storybooks and seeing the same error if I don't include `plugins: ['macros']` in the babel config.

**Comment by vzaidman** [comment]
> I'm using [require-context.macro](https://github.com/storybooks/require-context.macro) with React Native Storybook/storyshots and seeing the same error if I don't include `plugins: ['macros']` in the babel config.

The same thing happened to me.

**Comment by adriancbo** [comment]
React native doesn't support `path`.

**Comment by adriancbo** [comment]
Works for me after moving `plugins: ['macros']` to the root object in `babel.config.js`:

Before:
```
module.exports = {
  presets: [
    'module:metro-react-native-babel-preset',
  ],
  env: {
    development: {
      plugins: ['macros']
    },
    production: {
      plugins: ['transform-remove-console', 'macros']
    }
  }
};
```

After:
```
module.exports = {
  presets: [
    'module:metro-react-native-babel-preset',
  ],
  plugins: ['macros'],
  env: {
    production: {
      plugins: ['transform-remove-console']
    }
  }
};
```
